### ISSUE TITLE
Question about TransitionConstraintDegree in examples

### ISSUE THREAD

**Issue by wangtsiao** [facebook/winterfell#141]
Hi, I am delighted to find the winterfell repository, it is helpful to me. I am trying to understand the examples you gave. I found the `degree` variable in the air.rs difficult to learn. As the documentation describes that all trace columns have degree of 1 and when multiplying trace columns together, the degree increases by 1. Further, if a constraint involves multiplication of one trace column and one periodic column, we should use `with_cycles`.

Here in [merkle tree example](https://github.com/facebook/winterfell/blob/main/examples/src/merkle/air.rs#L38). The first six terms all have a degree of 5.
```rust
let degrees = vec![
    TransitionConstraintDegree::with_cycles(5, vec![HASH_CYCLE_LEN]),
    TransitionConstraintDegree::with_cycles(5, vec![HASH_CYCLE_LEN]),
    TransitionConstraintDegree::with_cycles(5, vec![HASH_CYCLE_LEN]),
    TransitionConstraintDegree::with_cycles(5, vec![HASH_CYCLE_LEN]),
    TransitionConstraintDegree::with_cycles(5, vec![HASH_CYCLE_LEN]),
    TransitionConstraintDegree::with_cycles(5, vec![HASH_CYCLE_LEN]),
    TransitionConstraintDegree::new(2),
];
```

However, when I further looked `evaluate_transition`, I found there are `rescue::enforce_round` constraints which have degree of 3 for the above first six terms. And then there are the following constraints.
```rust
// when hash_flag = 0, make sure accumulated hash is placed in the right place in the hash
// state for the next round of hashing. Specifically: when index bit = 0 accumulated hash
// must go into registers [0, 1], and when index bit = 0, it must go into registers [2, 3]
let hash_init_flag = not(hash_flag);
let bit = next[6];
let not_bit = not(bit);
result.agg_constraint(0, hash_init_flag, not_bit * are_equal(current[0], next[0]));
result.agg_constraint(1, hash_init_flag, not_bit * are_equal(current[1], next[1]));
result.agg_constraint(2, hash_init_flag, bit * are_equal(current[0], next[2]));
result.agg_constraint(3, hash_init_flag, bit * are_equal(current[1], next[3]));

// make sure capacity registers of the hash state are reset to zeros
result.agg_constraint(4, hash_init_flag, is_zero(next[4]));
result.agg_constraint(5, hash_init_flag, is_zero(next[5]));
```

The `hash_init_flag` comes from a periodic column. `not_bit` and `bit` comes from a normal trace column. Take the first term as an example. The degree here is 3, and plus  `rescue::enforce_round` constraints, the total degree should be 6.
```
result.agg_constraint(0, hash_init_flag, not_bit * are_equal(current[0], next[0]));
// hash_init_flag * not_bit * are_equal(current[0], next[0]);
```

I did not get how the degree 5 in code are determined.

In addition, the two terms below, each of them should have a degree of 4, then plus `rescue::enforce_round` constraints, the degree should be 7.
```
result.agg_constraint(2, hash_init_flag, bit * are_equal(current[0], next[2]));
result.agg_constraint(3, hash_init_flag, bit * are_equal(current[1], next[3]));
```

Can someone help me? appreciate.

**Comment by Nashtare** [comment]
> I found there are rescue::enforce_round constraints which have degree of 3 for the above first six terms
Merkle example uses the Rescue implementation over the 128 bit field implemented [here](https://github.com/facebook/winterfell/blob/main/examples/src/utils/rescue.rs). The degree of the forward s-box is 5 (the value by which we exponentiate each element). Hence the degree is 5, and not 3.

Hashing is applied when the periodic column `hash_flag` is on. When it is not, (i.e. `hash_init_flag` is on), we do not compute any Rescue permutation, but just ensure we placed the previously computed hash into the correct position. This is reflected by:

```
result.agg_constraint(0, hash_init_flag, not_bit * are_equal(current[0], next[0]));
result.agg_constraint(1, hash_init_flag, not_bit * are_equal(current[1], next[1]));
result.agg_constraint(2, hash_init_flag, bit * are_equal(current[0], next[2]));
result.agg_constraint(3, hash_init_flag, bit * are_equal(current[1], next[3]));
```

Here, `current[i]` and `next[j]` are both of degree 1. `are_equal` does not increase the degree (only subtraction, no multiplication). Hence the total degree is 2 (ignoring the periodic flag), as we multiply by either `bit` or `not_bit`. Because this degree is lower than the Rescue permutation degree, we indicate 5 when defining the transition contraint degrees.

**Comment by wangtsiao** [comment]
@Nashtare Thank you, sir. I got your explanation about the merkle tree example. But I am still confused about the rule of setting constraint degree. For example, I try to implement [The Collatz Sequence Execution Trace](https://medium.com/starkware/arithmetization-i-15c046390862) example in the Starkware Arithmization I blog for study.

Take 52 as the input, the trace table is shown below. 
![image](https://user-images.githubusercontent.com/70847926/218509167-48194957-05a3-482c-b9aa-a85855df63a1.png)

It is noted that the trace table has a length of 12, which is not a power of 2. So I just pad the trace table using zero, so that it has a length of 16. I am not sure whether this will have a pact on constraints' degrees.

![](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*zaajlXV-OwJ2Tbo0wpKdEA.png)

The collatz sequence CI statement has 4 constraints, the first two are boundary constraints, which will be expressed in `get_assertions` using a vector of `winterfell::Assertion`. The other two are normal constraints, which should correspond to a `Vec<TransitionConstraintDegree>`. Here I write the third constraint as a sum of `is_binary`. Since the sum operation does not increase the degree, we only consider the square operation in `is_binary`, then I determine the degree is 2.
```rust
// TransitionConstraintDegree::new(2)
for i in 0..TRACE_WIDTH {
    result[0] += is_binary(current[i]);
}
```

For the fourth constraint, the first column multiplies every six columns in the trace table, so I think the degree is 6. But it did not work. I am not sure whether the pad impacts the degree or if I made a false degree.

What's the right degree here, or should I pad the trace table? what's the right way to implement the collatz sequence example?

**Comment by Nashtare** [comment]
The degree of equation 4 is not 6.
Denoting $m_i = \sum\limits_{j=0}^{m-1} 2^j \cdot A_{i,j}$, we have that $m_i$ is of degree 1, and we can rewrite the eq. 3 as 
$\forall i < n-1: A_{i,0} \cdot \left\[ 3\cdot m_i + 1 - m_{i+1} \right\] + (1 - A_{i,0}) \cdot \left\[ m_i  - 2 \cdot m_{i+1} \right\] = 0$
This is an equation of degree 2.

**Comment by Nashtare** [comment]
You may want to familiarize yourself with [the Degree of a polynomial](https://en.wikipedia.org/wiki/Degree_of_a_polynomial), especially section _Behavior under polynomial operations_.

**Comment by wangtsiao** [comment]
Thank you, sir, you mentioned the behavior under polynomial operations, and I suddenly understood.

Now, I am sure the degree of the fourth constraint is 2. I changed it in my implementation code, however, it still panics with the below error. Seems I got something else wrong.
```
set assertion for initial number BaseElement(52) and step BaseElement(11)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[15, 15]`,
 right: `[15, 31]`: transition constraint degrees didn't match
expected: [ 15,  15]
actual:   [ 15,  31]', D:\devnow\paper-2023\winterfell\prover\src\constraints\evaluation_table.rs:221:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wangtsiao** [comment]
I upload my buggy code of the above example. Here is [diff](https://github.com/facebook/winterfell/compare/main...wangtsiao:winterfell:main).

**Comment by Nashtare** [comment]
In your evaluate_transition function, you wrote

```
        if num_from_state(current) == E::ONE {
            return;
        }
```

You cannot return early while evaluating the constraints, this doesn't mean anything valid algebraically speaking. When the prover constructs the original execution trace, it fills it with the actual values of the program. Here, it consists on the different number of the Collatz sequence, plus some additional variables like binary values.
To prove consistency of this trace without explicitly disclosing it, among other things (I insist on this), the prover will allow the verifier to check correctness of the constraints on two consecutive rows of an extended trace, defined over the LDE domain. On this domain, the relations look rubbish, i.e. you'll never (with high probability) get a cell element that equals to one, as you expect it in your code.

If you want your statement to be "I want to prove to you that starting number N reaches 1 under Collatz conjecture after k steps", you may want to include the number of steps k in your public inputs, and define a trace exemption (you can see how it is done in `vdf/exempt/air.rs` example), to define which rows should be ignored. This will maintain the algebraic properties when extending the trace to a larger domain (but I won't cover the details on how this works here) and should make your example work.

**Comment by wangtsiao** [comment]
Thank @Nashtare for the helpful answer! What a friendly community! 

Finally,  I completed my first STARK try using winterfell. Here is the fixed version collatz sequence example, I [update it](https://github.com/wangtsiao/winterfell/compare/cd76df242fcec8bab45efcdabf366fb0d8c76fbd...93efa210085216f8425fb3e8b15da441e913279a) for people who are interested.

Confusing resolved, so I close the issue.
