### ISSUE TITLE
Bug in f64 deserialization

### ISSUE THREAD

**Issue by maxgillett** [facebook/winterfell#145]
Unless I should be using another method for serialization, deserialization of zero values in this field does not work due to their canonical representation. The code below will panic with the error message: `InvalidValue("invalid field element: value 18446744069414584321 is greater than or equal to the field modulus")'`

```rust
use winter_math::{fields::f64::BaseElement, StarkField};
use winter_utils::Deserializable;
use winter_utils::SliceReader;

let bytes = BaseElement::from(0u8).as_int().to_le_bytes();
let mut reader = SliceReader::new(&bytes);
BaseElement::read_batch_from(&mut reader, 1).unwrap();
```

The issue is the following line, which should be changed to a greater than inequality:
https://github.com/facebook/winterfell/blob/cd76df242fcec8bab45efcdabf366fb0d8c76fbd/math/src/field/f64/mod.rs#L584

**Comment by Nashtare** [comment]
Technically, the error message is correct: M should not be an obtainable value if we serialized a correct element to start with. I think it may be better to alter the `as_int()` method, to ensure that the output after Montgomery -> canonical conversion is indeed canonical, i.e in `[0..M-1]`.
