### ISSUE TITLE
"Make sure layer queries hash into leaves of layer proof"

### ISSUE THREAD

**Issue by RobinLinus** [facebook/winterfell#158]
In [this line there's a TODO](https://github.com/facebook/winterfell/blob/8637a57db206ffb727b9222f006f10e96f81a2fd/fri/src/verifier/channel.rs#L87) saying _"make sure layer queries hash into leaves of layer proof"_. Sounds like the verifier currently does not verify that, or is it verified somewhere else?

**Comment by irakliyk** [comment]
This is more for a "debug" type check to make sure the code which actually computes hashes of leaves works correctly. The code that does this is located [here](https://github.com/facebook/winterfell/blob/main/fri/src/proof.rs#L316).

I do think that this structure is more complicated than it needs to be and I'd love to refactor it at some point (i.e., by abstracting away Merkle trees behind a `VectorCommitment` trait).

**Comment by irakliyk** [comment]
Closed by #285.
