### ISSUE TITLE
RandomCoin trait simplification

### ISSUE THREAD

**Issue by Al-Kindi-0** [facebook/winterfell#206]
The RandomCoin trait seems to be too flexible for its intended use. More specifically, the `reseed_with_int()` method is used only in the context of reseeding with the PoW produced through grinding. Moreover, the `draw_integers(...)` method is always run right after `reseed_with_int()` in order to generate query indices for the FRI protocol. Thus it seems reasonable to move the logic of `reseed_with_int()` inside of `draw_integers(...)`. More specifically, the signature of `draw_integers` should be:

```rust
fn draw_integers(
    &mut self,
    num_values: usize,
    domain_size: usize,
    pow_nonce: u64,
) -> Result<Vec<usize>, RandomCoinError> 
```

and the first thing `draw_integers` does is reseed with `pow_nonce` before generating the integers.

On the verifier side, the code could look like 
```rust
let pow_nonce = channel.read_pow_nonce();

// make sure the proof-of-work specified by the grinding factor is satisfied
if public_coin.check_leading_zeros(pow_nonce) < air.options().grinding_factor() {
    return Err(VerifierError::QuerySeedProofOfWorkVerificationFailed);
}

// draw pseudo-random query positions for the LDE domain from the public coin; in the
// interactive version of the protocol, the verifier sends these query positions to the prover,
// and the prover responds with decommitments against these positions for trace and constraint
// composition polynomial evaluations.
let query_positions = public_coin
    .draw_integers(air.options().num_queries(), air.lde_domain_size(), pow_nonce)
    .map_err(|_| VerifierError::RandomCoinError)?;
```

**Comment by irakliyk** [comment]
Closed by #214.
