### ISSUE TITLE
Will it be made into zkvm in the future?

### ISSUE THREAD

**Issue by nihaoqingtuan** [facebook/winterfell#211]
In the future, is there any plan to be compatible with rust or solidity, etc. as the front-end language to realize the whole process of zkvm?

**Comment by irakliyk** [comment]
Winterfell is a general-purpose STARK prover. It is pretty un-opinionated as to what it could be used for. But it is powerful enough so that arbitrary zkVMs can be built on top of it. For example, [Miden VM](https://github.com/0xPolygonMiden/miden-vm) uses Winterfell as its proving system.
