### ISSUE TITLE
Remove duplicate query check in FRI

### ISSUE THREAD

**Issue by Al-Kindi-0** [facebook/winterfell#216]
The analysis of FRI doesn't require the FRI query indices to not include duplicates i.e. it only requires that they are sampled randomly but doesn't require the sampling to be without replacement.
Thus it makes sense to simplify the FRI query generation by removing the duplicate check.

**Comment by irakliyk** [comment]
Makes sense! This would mean removing [these lines](https://github.com/facebook/winterfell/blob/main/crypto/src/random/default.rs#L223-L225), right?

**Comment by Al-Kindi-0** [comment]
Yes! I would say even starting with line 215 but we would need to change a few extra things in addition.
