### ISSUE TITLE
Suggestion: Remove outdated griffin hash implementation

### ISSUE THREAD

**Issue by Nashtare** [facebook/winterfell#252]
The current Griffin hash implementation was a deviation from an older design of the primitive family, which latest design has been completely broken for high branch count (typically the number of branches at use here), see https://eprint.iacr.org/2024/347.pdf (table 1, p18).

As such, I'd recommend simply removing the primitive from the library out of caution. I can open such PR if needed.

**Comment by irakliyk** [comment]
Thank you for bringing this up!

> I can open such PR if needed.

That would be awesome!
