### ISSUE TITLE
Does `Air::get_deep_composition_coefficients` assume that the proof is generated using an extension field?

### ISSUE THREAD

**Issue by 4l0n50** [facebook/winterfell#88]
This is not a real bug because I guess is at most generating an extra unused random coefficient. 
https://github.com/novifinancial/winterfell/blob/10a5f5ad90592889fe977c505012cd9f2159fb23/air/src/air/mod.rs#L512
In this line 3 coefficients are sampled for each trace polynomial: `\alpha_i` for the trace opening to `z`, `\beta_i` for the opening to `g*z`, and `\gamma_i` for showing that the trace poly is defined over the base field. If we are not working over an extension field then we don't need to prove the third statement. I guess this is not a big problem because, at most, the extra coefficient never gets read.

**Comment by irakliyk** [comment]
Thank you for noticing this! Yes, it's not really an issue as the "extra" random value is not used. But we should probably fix this in the future so that it doesn't cause confusion.
