### ISSUE TITLE
Indexing outside of bounds winterfell v0.3.0

### ISSUE THREAD

**Issue by nattrad** [facebook/winterfell#96]
Hello,

I tried running the STARK VDF (https://github.com/bobbinth/stark-vdf) using winterfell and when I run with `cargo run`, i get this: 

![image](https://user-images.githubusercontent.com/107082480/172498240-3c34b6e5-8192-48cc-a2e1-87c9a2536c18.png)

To fix I ran it with `cargo run --release` and get the following output:

![image](https://user-images.githubusercontent.com/107082480/172498365-75e4b28d-3bd7-4dc3-9b6c-89b0d748498c.png)

**Comment by irakliyk** [comment]
Fixed by #130
